# Generated by Django 3.2 on 2022-10-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ja', models.CharField(max_length=100)),
                ('color', models.CharField(default='#303967', max_length=7)),
                ('explanation', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('color', models.CharField(default='#303967', max_length=7)),
                ('page_hp', models.CharField(max_length=200)),
                ('page_doc', models.CharField(max_length=200)),
                ('page_github', models.CharField(max_length=200)),
                ('explanation', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('color', models.CharField(default='#303967', max_length=7)),
                ('page_hp', models.CharField(max_length=200)),
                ('page_doc', models.CharField(max_length=200)),
                ('page_github', models.CharField(max_length=200)),
                ('explanation', models.TextField(default='None')),
                ('language', models.ManyToManyField(to='index.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ja', models.CharField(max_length=100)),
                ('color', models.CharField(default='#303967', max_length=7)),
                ('explanation', models.TextField(default='None')),
                ('category', models.ManyToManyField(to='index.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#303967', max_length=7)),
                ('example_in', models.TextField(default='None')),
                ('example_out', models.TextField(default='None')),
                ('reference', models.TextField(default='None')),
                ('explanation', models.TextField(default='None')),
                ('category', models.ManyToManyField(to='index.Category')),
                ('language', models.ManyToManyField(to='index.Language')),
                ('library', models.ManyToManyField(to='index.Library')),
                ('topic', models.ManyToManyField(to='index.Topic')),
            ],
        ),
    ]
