# Generated by Django 3.2 on 2022-10-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='topic',
        ),
        migrations.AddField(
            model_name='spell',
            name='forwhat',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='spell',
            name='forwhat_ja',
            field=models.TextField(default='None'),
        ),
    ]
