# Generated by Django 3.2 on 2022-10-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20221029_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='category_name',
            field=models.CharField(default=models.ManyToManyField(to='index.Category'), max_length=100),
        ),
    ]
