# Generated by Django 3.2 on 2022-10-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_spell_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='category',
            field=models.ManyToManyField(related_name='category', to='index.Category'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='category_name',
            field=models.CharField(default=models.ManyToManyField(related_name='category', to='index.Category'), max_length=100),
        ),
    ]
