# Generated by Django 3.2 on 2022-10-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20221030_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='category',
            field=models.ManyToManyField(related_name='Category', to='index.Category'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='language',
            field=models.ManyToManyField(related_name='Language', to='index.Language'),
        ),
    ]
