# Generated by Django 3.2 on 2022-10-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20221030_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_number',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='language',
            name='language_number',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='library',
            name='language_number',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='library',
            name='library_number',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='spell',
            name='category_number',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='spell',
            name='language_number',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='spell',
            name='library_number',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='topic',
            name='category_number',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_number',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='spell',
            name='category',
            field=models.ManyToManyField(to='index.Category'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='language',
            field=models.ManyToManyField(to='index.Language'),
        ),
    ]
