# Generated by Django 3.2 on 2022-10-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20221030_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_number',
        ),
        migrations.RemoveField(
            model_name='language',
            name='language_number',
        ),
        migrations.RemoveField(
            model_name='library',
            name='language_number',
        ),
        migrations.RemoveField(
            model_name='library',
            name='library_number',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='category_number',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='language_number',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='library',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='library_number',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='category_number',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_number',
        ),
        migrations.AddField(
            model_name='spell',
            name='language_name',
            field=models.CharField(default='language_name', max_length=100),
        ),
        migrations.AddField(
            model_name='spell',
            name='library_github',
            field=models.CharField(default='library_github', max_length=100),
        ),
        migrations.AddField(
            model_name='spell',
            name='library_hp',
            field=models.CharField(default='library_hp', max_length=100),
        ),
        migrations.AddField(
            model_name='spell',
            name='library_name',
            field=models.CharField(default='library_name', max_length=100),
        ),
    ]
