# Generated by Django 3.2 on 2022-10-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20221030_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='language_name',
            field=models.CharField(default='language_name', max_length=100),
        ),
    ]
