# Generated by Django 3.2 on 2022-10-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_library_language_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='ext',
            field=models.CharField(default='.ext', max_length=100),
        ),
        migrations.AddField(
            model_name='language',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
    ]
