# Generated by Django 3.2 on 2022-10-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20221031_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='page_download',
            field=models.CharField(default='download', max_length=200),
        ),
    ]
