# Generated by Django 3.2 on 2022-10-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_language_page_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='library',
            field=models.ManyToManyField(to='index.Library'),
        ),
    ]
